PublicKey_Oracle: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJTrf0esw6dZxWcp5jXvsbnV3gEuAE4C6ByRqDGGdwbXfd4nly8Yra0ZmC0XiN/oj0xFKl2/80wp6nn3JCo+YtcCAwEAAQ==
PublicKey_Mysql: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJs1sxKOU7y2LTQmuQyyG8vL+r4M0CW8MmwSfHFmS5ThnUwlB8p3dHNQKroZCQukzg+GP3InMLBvJS2PlwAhpJMCAwEAAQ==

#单数据源
spring:
  datasource:
    oracle:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:orcl
      username: scott
      password: aBdPIswWEyrkl8LssWEdJbARsis4V2nz6fsgP/ea7LegqwuSfNze5t0WWa02eCJ8NJKxXj8w2g59z2rVTg4U4Q==
      type: com.alibaba.druid.pool.DruidDataSource

#配置多数据源
    mysql:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:orcl
      username: test2
      password: ggAxm4cfF7CHscBUYdlDQBNoUBiQzvDrNlG2AJ1L6nfJ2Yc4kEJd43gB7yW94f0U6sjBtPmf3r8EHIhQvSKkGw==
      type: com.alibaba.druid.pool.DruidDataSource



mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  #mapper-locations: classpath:mybatis/**/*Mapper.xml

pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql